
FROM maven:3.8.5-openjdk-8 AS builder

WORKDIR /app

COPY . .

RUN mvn clean -U
RUN mvn package

FROM openjdk:8-jdk-alpine

WORKDIR /app

COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8448

CMD ["java", "-jar", "app.jar"]